"""fix errors in razorpay_customer_id column

Revision ID: 25da3041f607
Revises: ecb6f62c6515
Create Date: 2024-05-29 00:26:41.367524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25da3041f607'
down_revision = 'ecb6f62c6515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_razorpay_customer_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_razorpay_customer_id_key', ['razorpay_customer_id'])

    # ### end Alembic commands ###
