"""adding a column name plan_id

Revision ID: 3596b6720403
Revises: 71e80f28b96a
Create Date: 2024-06-01 02:49:31.165125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3596b6720403'
down_revision = '71e80f28b96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('plan_id', sa.String(length=100), nullable=True))
    op.drop_column('payments', 'plain_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('plain_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('payments', 'plan_id')
    # ### end Alembic commands ###
