"""removing some rows in groups table for subscription

Revision ID: 3a84d2632a60
Revises: 99aac9d3101b
Create Date: 2024-06-03 23:05:42.901918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a84d2632a60'
down_revision = '99aac9d3101b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'subscription_link_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('subscription_link_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
