"""Adding required column in fields

Revision ID: 4ea5f9185960
Revises: 01b4f6c4643d
Create Date: 2024-04-29 21:27:20.827898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea5f9185960'
down_revision = '01b4f6c4643d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('required')

    # ### end Alembic commands ###
