"""currecting speling in payment_status

Revision ID: 5df6c190e5a9
Revises: a59600269bf3
Create Date: 2024-05-29 20:01:58.437203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df6c190e5a9'
down_revision = 'a59600269bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(), nullable=True))
        batch_op.drop_column('paymenet_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymenet_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
