"""updating rows in tables

Revision ID: 5f6da4ed7c51
Revises: 9fd4080b5d77
Create Date: 2024-06-04 02:43:37.588117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6da4ed7c51'
down_revision = '9fd4080b5d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'subscription')
    op.drop_column('groups', 'payment_status')
    op.drop_column('groups', 'plan_id')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_admin')
    op.add_column('groups', sa.Column('plan_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('subscription', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
