"""remove payment_link_url to GroupName

Revision ID: 689fa41108d6
Revises: 83ed5638a1b7
Create Date: 2024-05-29 18:44:37.167310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689fa41108d6'
down_revision = '83ed5638a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('payment_link_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
