"""Add payment_link_url to GroupName

Revision ID: 83ed5638a1b7
Revises: fba1c2cd0dbd
Create Date: 2024-05-29 18:38:05.276473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ed5638a1b7'
down_revision = 'fba1c2cd0dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('payment_link_url')

    # ### end Alembic commands ###
