"""Adding some columns in group table for subscription

Revision ID: 99aac9d3101b
Revises: f0c2b28e69b4
Create Date: 2024-06-03 22:53:56.986170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99aac9d3101b'
down_revision = 'f0c2b28e69b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.add_column('groups', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('plan_id', sa.String(length=100), nullable=True))
    op.add_column('groups', sa.Column('subscription', sa.String(length=50), nullable=False))
    op.add_column('groups', sa.Column('subscription_link_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'subscription_link_url')
    op.drop_column('groups', 'subscription')
    op.drop_column('groups', 'plan_id')
    op.drop_column('groups', 'payment_status')
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subscription', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_link_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    # ### end Alembic commands ###
