"""add a var name back_populates

Revision ID: 9b50c308dd0a
Revises: 74cdd6a85fbc
Create Date: 2024-04-09 01:06:32.887332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b50c308dd0a'
down_revision = '74cdd6a85fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.alter_column('dataformat_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.alter_column('dataformat_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
