"""updating row in groups table 

Revision ID: 9fd4080b5d77
Revises: d2401b17dfb7
Create Date: 2024-06-04 00:31:34.932301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd4080b5d77'
down_revision = 'd2401b17dfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
