"""Add payment_link_url to GroupName

Revision ID: a59600269bf3
Revises: 689fa41108d6
Create Date: 2024-05-29 18:51:07.874881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59600269bf3'
down_revision = '689fa41108d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('payment_link_url')

    # ### end Alembic commands ###
