"""adding backref

Revision ID: bde2c0f5488e
Revises: 220c3ac32c98
Create Date: 2024-04-06 01:54:14.073260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde2c0f5488e'
down_revision = '220c3ac32c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataformats', schema=None) as batch_op:
        batch_op.drop_constraint('dataformats_field_id_fkey', type_='foreignkey')
        batch_op.drop_column('field_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataformats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('dataformats_field_id_fkey', 'fields', ['field_id'], ['id'])

    # ### end Alembic commands ###
