"""Create 2 new columns name created_data and updated_data

Revision ID: daff9ccfe664
Revises: 8d7fd6140245
Create Date: 2024-04-03 19:37:10.375439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daff9ccfe664'
down_revision = '8d7fd6140245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_data', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_data', sa.DateTime(), nullable=False))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_data', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_data', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('updated_data')
        batch_op.drop_column('created_data')

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('updated_data')
        batch_op.drop_column('created_data')

    # ### end Alembic commands ###
