"""Adding anew table name dataformats

Revision ID: ea692b13a585
Revises: 9f24ba1bccfb
Create Date: 2024-04-05 22:52:55.722064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea692b13a585'
down_revision = '9f24ba1bccfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataformats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataformats')
    # ### end Alembic commands ###
