"""Adding new column name razorpay_customer_id

Revision ID: ecb6f62c6515
Revises: 95bf73e91df4
Create Date: 2024-05-28 23:37:28.084317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb6f62c6515'
down_revision = '95bf73e91df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['razorpay_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('razorpay_customer_id')

    # ### end Alembic commands ###
