"""removing a column name price

Revision ID: f0c2b28e69b4
Revises: 3596b6720403
Create Date: 2024-06-01 02:56:37.434221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c2b28e69b4'
down_revision = '3596b6720403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
