"""adding column and create relationship in dataformats in fields

Revision ID: f1c80303af3b
Revises: 78f566440191
Create Date: 2024-04-06 01:25:40.739626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c80303af3b'
down_revision = '78f566440191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataformats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('dataformats_field_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fields', ['field_id'], ['id'])
        batch_op.drop_column('field')

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformat', sa.String(), nullable=False))
        batch_op.drop_constraint('fields_dataformat_id_fkey', type_='foreignkey')
        batch_op.drop_column('dataformat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformat_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fields_dataformat_id_fkey', 'dataformats', ['dataformat_id'], ['id'])
        batch_op.drop_column('dataformat')

    with op.batch_alter_table('dataformats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dataformats_field_fkey', 'fields', ['field'], ['id'])
        batch_op.drop_column('field_id')

    # ### end Alembic commands ###
