"""Removing some columns and association dataType table

Revision ID: 0b58336eed96
Revises: 33cf8f90bec6
Create Date: 2024-03-12 02:03:45.625085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b58336eed96'
down_revision = '33cf8f90bec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_constraint('datatype_field_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('datatype_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('group_id')
        batch_op.drop_column('string')
        batch_op.drop_column('boolean')
        batch_op.drop_column('field_id')
        batch_op.drop_column('integer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datatype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integer', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('field_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('boolean', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('string', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('datatype_group_id_fkey', 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key('datatype_field_id_fkey', 'fields', ['field_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
