"""Add one column field_key for update field id before session commited

Revision ID: 277c3b5bccdd
Revises: 
Create Date: 2024-03-16 01:36:22.296844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277c3b5bccdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_key', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('field_key')

    # ### end Alembic commands ###
