"""changing datatype column name into dataformat

Revision ID: 2b432bb47e0a
Revises: 3e7c478f2768
Create Date: 2024-03-12 22:11:43.263894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b432bb47e0a'
down_revision = '3e7c478f2768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformat', sa.String(), nullable=False))
        batch_op.drop_column('datatype')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformat', sa.String(), nullable=False))
        batch_op.drop_column('datatype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datatype', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('dataformat')

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datatype', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('dataformat')

    # ### end Alembic commands ###
