"""fixing some errors for dataformat column

Revision ID: 2f4090c9f4e1
Revises: f27bf3a474f8
Create Date: 2024-04-06 01:13:20.983918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4090c9f4e1'
down_revision = 'f27bf3a474f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('dataformat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformat', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
