"""Removing type for some time

Revision ID: 32957740bd3b
Revises: 0b58336eed96
Create Date: 2024-03-12 02:25:10.642476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32957740bd3b'
down_revision = '0b58336eed96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
