"""adding one column datatype

Revision ID: 3e7c478f2768
Revises: 
Create Date: 2024-03-12 21:56:26.384003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7c478f2768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datatype')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datatype', sa.String(), nullable=False))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datatype', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('datatype')

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('datatype')

    op.create_table('datatype',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='datatype_pkey')
    )
    # ### end Alembic commands ###
