"""update column name is_defalut

Revision ID: 40a31c311c4c
Revises: 8cd10d47bab2
Create Date: 2024-02-28 03:59:38.940117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a31c311c4c'
down_revision = '8cd10d47bab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.drop_column('default')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
