"""changing some cloumns

Revision ID: 4628170ae412
Revises: 2f4090c9f4e1
Create Date: 2024-04-06 01:18:57.214135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4628170ae412'
down_revision = '2f4090c9f4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformats', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fields_dataformat_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dataformats', ['dataformats'], ['id'])
        batch_op.drop_column('dataformat_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformat_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fields_dataformat_id_fkey', 'dataformats', ['dataformat_id'], ['id'])
        batch_op.drop_column('dataformats')

    # ### end Alembic commands ###
