"""Add new column namw input_type

Revision ID: 74cdd6a85fbc
Revises: bde2c0f5488e
Create Date: 2024-04-08 20:25:00.613107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74cdd6a85fbc'
down_revision = 'bde2c0f5488e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataformats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataformats', schema=None) as batch_op:
        batch_op.drop_column('input_type')

    # ### end Alembic commands ###
