"""changing name a column dataformats into dataformat

Revision ID: cd572b53fa45
Revises: f1c80303af3b
Create Date: 2024-04-06 01:30:52.321953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd572b53fa45'
down_revision = 'f1c80303af3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('dataformat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataformat', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
