"""Remove field_key column

Revision ID: f2701733768d
Revises: f9c27b038777
Create Date: 2024-04-02 22:45:53.230037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2701733768d'
down_revision = 'f9c27b038777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('field_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_key', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
