"""Changing in Field key

Revision ID: ff56bb3976db
Revises: d7d9ba6afcbc
Create Date: 2024-03-19 19:21:31.730591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff56bb3976db'
down_revision = 'd7d9ba6afcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.alter_column('field_key',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.alter_column('field_key',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
